### ISSUE TITLE
Add global var with layout sizes

### ISSUE THREAD

**Issue by johnnyduke** [comongroup/cylinder#21]
Since Cylinder adds a 'layout' class to the body tag accordingly with the bootstrap responsive breakpoints, this values should be stored in a global var.

Example: Using the slick plugin with responsive breakpoints

```
var slick_options = {
    responsive: [
        {
            breakpoint: comon.layout[xl]
           ...
        }
    ]
}
```
It will also be useful to define the breakpoints. If we are using a different framework (not bootstrap) the layout-class will not be in accordance with the css framework.

**Comment by luisjs** [comment]
Possibly fixed with 1a5b41b8bd57d997f239e87acdfecf3043e16e09:

- `resize.getRule(name)` to fetch a single rule;
- `resize.getCurrentRules(objects)` to return a list of currently active rules. If `true` is passed to the method, a dictionary of active rules will be passed instead.

As for defining the breakpoints, Cylinder only provides a default set of rules based on Bootstrap 4 for convenience. Anyone is free to add and manage their own rules in their projects using the `resize.addRule` method. However, to make this process easier, the default rules have been renamed from `layout-*` to `bs4-*` instead.
